### ISSUE TITLE
Integration with ownCloud

### ISSUE THREAD

**Issue by hitam4450** [PVHL/Woas#1]
Hi Paul,

I suggest integrating WOAS with OwnCloud. 
I did some experiments to integrate the HTML - file by myself, but I failed, since I am not very familiar with the 'internals' of WOAS!

regards, hitam4450 (Ireng)

**Comment by PVHL** [comment]
Hi Ireng -- good to see you here. I'm coming to some final decisions on what I'm willing to do with Woas, as I've already mentioned  on SourceForge. I looked at OwnCloud after you mentioned it and discovered that I had researched it at some point in the past. I agree it would be useful, as would Dropbox, et al. I've also long wanted to do it -- dynamic updating to a server -- but haven't got there yet, partly because my needs have changed somewhat. But also because the core purpose of the original WoaS (and what originally attracted me to it) was to be a wiki in a self-hosted HTML file you could carry around and work offline with, and update on any computer. Modern browsers have made that near impossible (or will soon) without a lot of messing around, or a local server.

As usual, Jeremy over at [TiddlyWiki](http://tiddlywiki.com/) has come up with most of the same ideas I had -- but he actually implemented them! Seriously; both a [node version](http://tiddlywiki.com/#TiddlyWiki%20on%20Node.js:%5B%5BTiddlyWiki%20on%20Node.js%5D%5D%20Platforms) and a kind of [node/Chrome hybrid desktop version](https://github.com/Jermolene/TiddlyDesktop/releases) that works on all platforms. (I had also looked at [node-webkit](https://github.com/nwjs/nw.js) as a possible solution, and Jeremy's efforts would give me a tutorial and a place to start.) And a nice [TiddlyWeb adapter](http://tiddlywiki.com/#TiddlyWiki%20in%20the%20Sky%20for%20TiddlyWeb) that is open source and can sync a local file with the server and vice versa.

If I'm going to update Woas it may be with the desktop node/chrome application: much easier to write and maintain when only one browser version is being considered. I want to spend some time looking at TW5's new codebase again before deciding what to do. Woas could potentially become a plugin for TW5 that gives it Woas functionality and feel, and I only have to write and maintain the plugin(s). (I can then also contribute to their project.) Whatever, I'd like to leave a working Woas behind me, so I'll try to finish that ... though the house I live in, the house that allows me the contract I live by, is being sold, so life becomes somewhat hectic again for a while. Just trying to let everyone know where I'm coming from.

Anyway, thanks for the comment. I will look into it, but don't want to leave tickets open for feature requests.

If you can show me what you were trying to do I'll see if I can help.

Cheers!

**Comment by hitam4450** [comment]
Hi Paul!
First of All I would like to convey my best wishes to you for 2016, Success & And of course good health!
I am sorry, that I didn't respond earlier to your long awaited comment, expressing your dedication to develop & maintain WOAS in the future. I was very busy lately and in my private life were many changes, I also had to adopt to, which of course took some time.

However, I am back again to Github and of course back to WOAS.

The base idea of WOAS - to carry around all vital information in ONE file - still make me recommend it to all of my friends and still use it on a daily basis. One file I use for my business, one for my private matters.
In this case, nothing will be mixed up.

However, one thing is still difficult for me:
My business file consist of many tables, which hold links to different pages and sub pages. 
I also discovered, that some pages exit twice, in different branches of the file.
A simple  tool for graphical ??? documenting the links from top to bottom and all relations of the different pages would be most appreciated and helpful to cleanup existing files and structure things more clearly.

I certainly use the available toolbox for orphan pages, all pages, etc. However, a picture tells more than a thousand words, isn't it?

I really appreciate the continuing discussion with you and I will be more responsive now!

regards, hitam4450 (aka ireng)
