### ISSUE TITLE
Cannot Save new content anymore

### ISSUE THREAD

**Issue by hitam4450** [PVHL/Woas#2]
Hi, I use woas  **0.13 beta 1** with FF 54 and UBUNTU 16.04!

Editing a page and saving it, returns in the enclosed error message! reloading the page does not show any changes at all!

What happened and Why ??

The tiddlySver.jar and the html file are located in the same directory!

starting java -jar TiddlySaver.jar results in the error message:
woas# java -jar TiddlySaver.jar
kein Hauptmanifestattribut, in TiddlySaver.jar

jre1.8.0-131_1.8.0131-1_amd64.deb has been installed!

![woas](https://user-images.githubusercontent.com/9738727/28880414-3bd03054-77a5-11e7-8ce9-e74a5243fa43.png)
![woas2](https://user-images.githubusercontent.com/9738727/28880415-3be0419c-77a5-11e7-8d2f-4baaa3f436d1.png)

![woas3](https://user-images.githubusercontent.com/9738727/28880630-f3ed9a5a-77a5-11e7-9e7a-1926e89b978a.png)

**Comment by PVHL** [comment]
Hi. This is the wrong place to ask this as it is still a SF project. Also, afraid I don't read your language.

I can't help with TiddlySaver at the moment, other than to suggest you make sure you're using the latest version of it on my SF Woas project, as it's different from the current TiddlyWiki one, and that you read my notes on setting up for Java.  Sorry. (You could also downgrade Java to an earlier working version if you are only using it for Woas.)

There is a solution that I use in Firefox: [TiddlyFox](https://addons.mozilla.org/en-US/firefox/addon/tiddlyfox/). I may still write a WoasFox some day so that binary/image files can also be saved, but I'm currently busy with an NW.js app with similar capabilities and the release of a song collection.

IE also works without add-ons, at least in Windows 7 and earlier, but that doesn't help you on Linux.

Browsers have done their best over the last few years to prevent programs like Woas from working. I've read that TiddlyFox may not be able to work soon. That, and all the browser inconsistencies, makes it difficult to keep working on it in public.

Hopefully you can use TiddlyFox. Let me know if there's any issues, but I believe 13.1 has support for it; I use it when on Firefox without issues, even on Android.

Cheers, Paul.

**Comment by hitam4450** [comment]
Dear Paul, 
many thanks for your comprehensive answer. i really appreciate it, ever since we met through the woas project! I enclosed the screen shot of the tiddlywiki extension in FF 54.0 ! I certainly will investigate even more the problem and will report back here, since I am busy with other github projects on a daily basis!

regards, hitam4450

I really appreciate your continuous work on woas!


![tiddly](https://user-images.githubusercontent.com/9738727/29061220-3c9be2d6-7c1d-11e7-95d2-75dbc171607c.png)

**Comment by PVHL** [comment]
I noticed you were using FF and so suggested the TiddlyFox extension. I believe it works on all OS. As I mentioned, I use it on Windows 7 and Android.

I appreciate the kind words.

**Comment by hitam4450** [comment]
I tried installed the TiddlyFox extension, it it still does not want save any content to file !

regards, hitam4450

**Comment by PVHL** [comment]
I just took a look at the Woas 0.13.0 beta 1 code and the latest TiddlyFox code. All the tests for saving are still in TiddlyFox and still work in Woas, but the extension is not recognizing the file for some reason. Not sure when I have time to look at this, as it could take a while to discover what's going on. Very strange.

As for Java, if it ***just stopped working*** I don't know what to tell you. This same file, TiddlySaver and Java file/setup used to work for you?

**Comment by PVHL** [comment]
Actually, [I recall reading](https://github.com/TiddlyWiki/TiddlyFox/issues/55) someone saying they had fixed it for 54 (I'm using the bleeding-edge 55 currently, but really thought I had tested saving when I installed it and it worked; guess I'm misremembering).

I don't want to follow his advice right now, but you might. Otherwise, you could try the [previous version](https://addons.mozilla.org/en-us/firefox/addon/tiddlyfox/versions/) after downgrading to FF51.

Fact is, the [extension will not work much longer](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Getting_Started_%28jpm%29) - it will be completely disabled by FF57 on November 14th.

It still amazes me -- and has for years -- that browsers won't allow trusted html files to save to the same directory or a subdirectory of it once permission is granted. What are they protecting us foolish users from? And when did they become our nanny?

NW.js or Electron seems a far better choice. It took me just a few minutes to get Woas working in NW.js. I could document how, but can't support at all until/unless I release a new version using it, and I won't do that without rewriting and organizing the current codebase. It's a mess.

We would still be able to share content, but it would be via WSIF files.

Gotta run. Sorry to not be more help. I'll take a look at TiddlyFox when I get a chance, especially to see if Jeremy is developing a WebExtension for TiddlyWiki.

(Update: seems WebExtensions can only save files by talking to another specially written 'native' app. Seriously. In what way is that more secure than getting user permission to access and store files programmatically? Crazy.

They've also made it that you must use registry keys in Windows. I'm not interested in developing such an extension, nor will I use it unless I have no alternative; I try to stay portable, though a PortableApps app could be used. Given IE11 works fine -- it can even be tricked into saving binary files -- and I'm usually on Windows 7, working on this makes no sense to me, especially given my current circumstances and needs. Node makes sense, so I'll put my efforts there when/if I'm able.)

**Comment by PVHL** [comment]
OK, it's a timing issue. Something's changed with the new TiddlyFox and it's not setting the required div until too late (about 300mS or so on my system).

If you only use the normal Woas (not the external WSIF) I can give you a quick fix. Let me know.

Fixing it properly will probably take a fair bit more time and possibly some interaction with Jeremy.

Let me know.

**Comment by PVHL** [comment]
I realize what you wanted was Java, and I'll add some thoughts below, but here is a quick hack to get TiddlyFox working. 

For `0.13.0 beta 1` find line `11458` (same code for the other betas; slightly different locations):
```
	// try to use Java if there is no other option
```
replace with:
```
	var that = this;
	setTimeout(function(){that._on_load2()}, 200);
}

woas._on_load2 = function() {
	// try to use Java if there is no other option
```
My laptop is quite old and 200mS works for me; you may find a better value, but I can live with a tiny delay in loading to keep using TiddlyFox. I may find a better fix, but this works for now. I'll be releasing a quick update soon on SourceForge. PLEASE, let me know if this works for you -- it will help others.

OK, Java. Please see my notes on the ` Loading and Saving` Woas page. The TiddlySaver plugin's certificate has probably expired; it's been about 5 years. I did the required work for Jeremy last time, but the signing is/was done by a third party that owns copyright on the TiddlyWiki code; I haven't the time to do so this time. (I get almost no feedback as to how many are actually using my Woas version and if they need/use Java or TiddlyFox, and I'm in the midst of other more important things. It hurts that I can't get people to use my working version instead of downloading the broken original.)

Anyway, the page has instructions for using the unsigned version of the TiddlySaver app. This might probably fix your problem. Again, PLEASE let me know if this works for you; I simply haven't the time or resources to try it myself right now, but I'll report your findings on SF and in an updated file..

Hope this helps.
